/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app

class App {
  val greeting: String
    get() {
      return "Hello World!"
    }
}

/*
  The main function is the entry point for the application.
*/
fun main() {
  println(App().greeting)
}
